RandomActs/Controllers/ActActorController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RandomActs.Models;

namespace RandomActs.Controllers
{
    public class ActActorController : Controller
    {
		private readonly IRandomActActorRepository actActorRepository;
        private readonly IRandomActRepository actRepository;
        private readonly IRandomActorRepository actorRepository;

        public ActActorController() : this(new RandomActActorRepository(), 
                                            new RandomActRepository(),
                                            new RandomActorRepository())
        {
        }

        public ActActorController(IRandomActActorRepository ActActorRepository,
            IRandomActRepository ActRepository,
            IRandomActorRepository ActorRepository)
        {
            this.actActorRepository = ActActorRepository;
            this.actRepository = ActRepository;
            this.actorRepository = ActorRepository;
        }

        public ActionResult AttendeeList(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            RandomAct randomAct = actRepository.Find(id.Value);
            if (randomAct == null)
            {
                return HttpNotFound();
            }

            ViewBag.RandomActId = id.Value;
            ViewBag.RandomActTitle = randomAct.Title;
            ViewBag.MaxActors = randomAct.MaxActors;
            if (randomAct.Actors.Count < randomAct.MaxActors)
            {
                ViewBag.Registered = randomAct.Actors.Count;
                ViewBag.WaitListed = 0;
                ViewBag.MaxedOut = false;
            }
            else
            {
                ViewBag.Registered = randomAct.MaxActors;
                ViewBag.WaitListed = randomAct.Actors.Count - randomAct.MaxActors;
                ViewBag.MaxedOut = true;
            }
            var randomactactors = actActorRepository.FilterByActId(id.Value);
            return View(randomactactors.ToList());
        }

        // GET: /ActActor/Register
        public ActionResult Register(int? id)
        {
            return GoRegister(id, false);
        }

        // GET: /ActActor/WaitList
        public ActionResult WaitList(int? id)
        {
            return GoRegister(id, true);
        }

        private ActionResult GoRegister(int? id, bool waitList)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            RandomAct randomAct = actRepository.Find(id.Value);
            if (randomAct == null)
            {
                return HttpNotFound();
            }

            RandomActActor newRandomActActor = new RandomActActor();
            newRandomActActor.RandomActId = id.Value;
            newRandomActActor.WaitList = waitList;
            ViewBag.RandomActTitle = randomAct.Title;
            ViewBag.RandomActorId = new SelectList(actorRepository.All, "RandomActorId", "FullName");

            return View("Register", newRandomActActor);
        }

        // POST: /ActActor/Register
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register([Bind(Include = "RandomActActorId,RandomActId,RandomActorId,WhatICanBring,Message,WaitList")] RandomActActor randomactactor)
        {
            if (actActorRepository.IsActorRegisteredAlready(randomactactor.RandomActId, randomactactor.RandomActorId))
                ModelState.AddModelError(string.Empty, "This actor already registered for event.");
            else if (ModelState.IsValid)
            {
                actActorRepository.InsertOrUpdate(randomactactor);
                actActorRepository.Save();
                return RedirectToAction("AttendeeList", new { id = randomactactor.RandomActId });
            }

            ViewBag.RandomActTitle = actRepository.Find(randomactactor.RandomActId).Title;
            ViewBag.RandomActorId = new SelectList(actorRepository.All, "RandomActorId", "FullName", randomactactor.RandomActorId);
            return View("Register", randomactactor);
        }

        // GET: /ActActor/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RandomActActor randomactactor = actActorRepository.Find(id.Value);
            if (randomactactor == null)
            {
                return HttpNotFound();
            }
            ViewBag.RandomActorId = new SelectList(actorRepository.All, "RandomActorId", "FullName", randomactactor.RandomActorId);
            return View(randomactactor);
        }

        // POST: /ActActor/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="RandomActActorId,RandomActId,RandomActorId,WhatICanBring,Message,WaitList")] RandomActActor randomactactor)
        {
            if (ModelState.IsValid)
            {
                actActorRepository.InsertOrUpdate(randomactactor);
                actActorRepository.Save();
                return RedirectToAction("AttendeeList", new { id = randomactactor.RandomActId });
            }
            ViewBag.RandomActorId = new SelectList(actorRepository.All, "RandomActorId", "FullName", randomactactor.RandomActorId);
            return View(randomactactor);
        }

        // GET: /ActActor/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RandomActActor randomactactor = actActorRepository.Find(id.Value);
            if (randomactactor == null)
            {
                return HttpNotFound();
            }
            return View(randomactactor);
        }

        // POST: /ActActor/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            int randomActId = actActorRepository.Find(id).RandomActId;
            actActorRepository.Delete(id);
            actActorRepository.Save();
            return RedirectToAction("AttendeeList", new { id = randomActId });
        }
    }
}

RandomActs/Controllers/ActController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RandomActs.Models;

namespace RandomActs.Controllers
{
    public class ActController : Controller
    {
		private readonly IRandomActRepository actRepository;

        public ActController() : this(new RandomActRepository())
        {
        }

        public ActController(IRandomActRepository RandomActRepository)
        {
            this.actRepository = RandomActRepository;
        }

        // GET: /Home/
        public ActionResult Index()
        {
            return View(actRepository.All);
        }

        // GET: /Home/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Home/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="RandomActId,Title,Description,Location,Address,City,State,StartTime,EndTime,MaxActors")] RandomAct randomact)
        {
            if (ModelState.IsValid)
            {
                actRepository.InsertOrUpdate(randomact);
                actRepository.Save();
                return RedirectToAction("Index");
            }

            return View(randomact);
        }

        // GET: /Home/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RandomAct randomact = actRepository.Find(id.Value);
            if (randomact == null)
            {
                return HttpNotFound();
            }
            return View(randomact);
        }

        // POST: /Home/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="RandomActId,Title,Description,Location,Address,City,State,StartTime,EndTime,MaxActors")] RandomAct randomact)
        {
            if (ModelState.IsValid)
            {
                actRepository.InsertOrUpdate(randomact);
                actRepository.Save();
                return RedirectToAction("Index");
            }
            return View(randomact);
        }

        // GET: /Home/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RandomAct randomact = actRepository.Find(id.Value);
            if (randomact == null)
            {
                return HttpNotFound();
            }
            return View(randomact);
        }

        // POST: /Home/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            actRepository.Delete(id);
            actRepository.Save();
            return RedirectToAction("Index");
        }

        public ActionResult About()
        {
            return View("About");
        }

        public ActionResult Contact()
        {
            return View("Contact");
        }


    }
}

RandomActs/Views/Act/About.cshtml
@{
    ViewBag.Title = "About";
}

<h2>About</h2>

<div style="color:blue;font-size:larger;">
    This site is dedicated to Random Acts of Kindness and
    bringing together volunteers with the acts.
</div>

RandomActs/Views/Act/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<h2>Contact</h2>

<div style="color:blue;font-size:larger;">
    Contact us at <a href="mailto:info@raok.org">info@raok.org</a>
</div>

RandomActs/Views/Act/Create.cshtml
@model RandomActs.Models.RandomAct

@{
    ViewBag.Title = "New Random Act";
}

<h2>New Act</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Random Act</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Title, new { style = "width: 400px" })
                @Html.ValidationMessageFor(model => model.Title)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, new { style = "width: 400px" })
                @Html.ValidationMessageFor(model => model.Description)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Location, new { style = "width: 400px" })
                @Html.ValidationMessageFor(model => model.Location)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Address, new { style = "width: 400px" })
                @Html.ValidationMessageFor(model => model.Address)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City)
                @Html.ValidationMessageFor(model => model.City)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.State, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.State, new { style = "width: 50px" })
                @Html.ValidationMessageFor(model => model.State)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartTime, new { @class = "control-label col-md-2 picker" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.StartTime, new { style = "width: 200px" })
                @Html.ValidationMessageFor(model => model.StartTime)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndTime, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.EndTime, new { style = "width: 200px" })
                @Html.ValidationMessageFor(model => model.EndTime)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaxActors, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.MaxActors, new { style = "width: 50px" })
                @Html.ValidationMessageFor(model => model.MaxActors)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RandomActs/Views/Act/Delete.cshtml
@model RandomActs.Models.RandomAct

@{
    ViewBag.Title = "Delete a Random Act";
}

<h2>Cancel an Act</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>RandomAct</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaxActors)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaxActors)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

RandomActs/Views/Act/Details.cshtml
@model RandomActs.Models.RandomAct

@{
    ViewBag.Title = "Random Act Details";
}

<h2>Act Details</h2>

<div>
    <h4>RandomAct</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaxActors)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaxActors)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.RandomActId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

RandomActs/Views/Act/Edit.cshtml
@model RandomActs.Models.RandomAct

@{
    ViewBag.Title = "Edit a Random Act";
}

<h2>Edit an Act</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
     <div class="form-horizontal">
        <h4>Random Act</h4>
        <hr />
       @Html.ValidationSummary(true)

        @Html.HiddenFor(model => model.RandomActId)
        <div class="form-group">
            @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Title, new { style = "width: 400px" })
                @Html.ValidationMessageFor(model => model.Title)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, new { style = "width: 400px" })
                @Html.ValidationMessageFor(model => model.Description)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Location, new { style = "width: 400px" })
                @Html.ValidationMessageFor(model => model.Location)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Address, new { style = "width: 400px" })
                @Html.ValidationMessageFor(model => model.Address)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City)
                @Html.ValidationMessageFor(model => model.City)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.State, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.State, new { style = "width: 50px" })
                @Html.ValidationMessageFor(model => model.State)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartTime, new { @class = "control-label col-md-2 picker" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.StartTime, new { style = "width: 200px" })
                @Html.ValidationMessageFor(model => model.StartTime)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndTime, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.EndTime, new { style = "width: 200px" })
                @Html.ValidationMessageFor(model => model.EndTime)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaxActors, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.MaxActors, new { style = "width: 50px" })
                @Html.ValidationMessageFor(model => model.MaxActors)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RandomActs/Views/Act/Index.cshtml
@model IEnumerable<RandomActs.Models.RandomAct>

@{
    ViewBag.Title = "Random Acts";
}

<h2>Random Acts of Kindness</h2>

<p>
    @Html.ActionLink("New Event", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Location)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.State)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndTime)
        </th>
        <th>
            Max
        </th>
        <th>
            Registered
        </th>
        <th>
            Wait Listed
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    bool boolWaitList = (item.MaxActors != null && item.Actors.Count >= item.MaxActors);
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Location)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.City)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.State)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EndTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MaxActors)
        </td>
        <td>
            @(item.Actors.Count > item.MaxActors ? item.MaxActors : item.Actors.Count)
        </td>
        <td>
            @(item.Actors.Count > item.MaxActors ? item.Actors.Count - item.MaxActors : 0)
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.RandomActId }) |
            @Html.ActionLink("Cancel", "Delete", new { id = item.RandomActId }) |
            @Html.ActionLink("Attendees", "AttendeeList", "ActActor", new { id = item.RandomActId }, null)
        </td>
    </tr>
}

</table>